name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        shell: bash
      - run: npm run lint
        shell: bash
      - run: npm test -- --coverage
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.os }}
          path: coverage
